version: "3.7"

services:
  products_api:
    container_name: 'products_api'
    restart: always
    build: ./
    ports: 
      - 5050:5050
    volumes: 
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on: 
      - products_db
  
  products_db:
    container_name: 'products_db'
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'products'
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - products_db:/var/lib/postgresql/data
volumes: 
  products_db : {}

