version: "3.7"

services:
  store_api:
    container_name: 'store_api'
    restart: always
    build: ./
    ports: 
      - 5050:5050
    volumes: 
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on: 
      - store_db
    env_file: 
      - .env
  store_db:
    container_name: 'store_db'
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=baqala_store_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes: 
      - store_db:/var/lib/postgresql/data
volumes: 
  store_db : {}

