version: "3.7"

services:
  user_api:
    container_name: 'user_api'
    restart: always
    build: ./
    ports: 
      - 5051:5051
    volumes: 
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on: 
      - user_db
    env_file: 
      - .env
  user_db:
    container_name: 'user_db'
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=baqala_user_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes: 
      - user_db:/var/lib/postgresql/data
volumes: 
  user_db : {}

